[build-system]
requires = [
  'setuptools>=61.0.0'
]
build-backend = 'setuptools.build_meta'

[project]
name = 'satellite-camera-viewer'
version = '0.4.0'
description = 'A full sky star chart showing the view from a camera mounted on a earth orbiting satellite'
readme = 'README.md'
requires-python = '>=3.10'
license = 'MIT'
license-files = ['LICENSE' ]
authors = [ { name = 'Martin J Levy', email = 'mahtin@mahtin.com' } ]
dependencies = [
  'astropy>=6.0.0',
  'healpy>=1.19.0',
  'matplotlib>=3.10.3',
  'numpy==1.26.4',
  'pyvista>=0.47.3',
  'requests>=2.33.0',
  'scipy>=1.17.1',
  'sgp4>=2.25',
  'spherical-geometry>=1.4.0',
  'pillow==10.4.0',
]

[tool.setuptools.packages.find]
where = ['src/']
include = [ 'SatelliteCameraViewer', 'SatelliteCameraViewer.SatelliteCamera', 'SatelliteCameraViewer.Cubesat', 'SatelliteCameraViewer.StarCatalog', 'SatelliteCameraViewer.CameraImage' ]

[project.optional-dependencies]
dev = [ 'pytest>=7.0.0' ]

[project.scripts]
satellitecameraviewer = 'SatelliteCameraViewer.satellite_camera_viewer:satellite_camera_viewer'

[project.urls]
'Documentation' = "https://example.com"
'Homepage' = 'https://github.com/mahtin/satellite-camera-viewer'
'Repository' = 'https://github.com/mahtin/satellite-camera-viewer'
'Bug Tracker' = 'https://github.com/mahtin/satellite-camera-viewer/issues'
'Changelog' = "https://github.com/mahtin/satellite-camera-viewer/blob/main/CHANGELOG.md"

